name: Build, Run, and Test Go Binary

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-binary:
    runs-on: ubuntu-latest

    steps:
    # 1. Check out the repository code
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. Install and set up the Go environment
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.26' # Specify your preferred Go version
        cache: true        # Enables caching for faster subsequent builds

    # 3. Compile the Go application into an executable binary
    - name: Build Go Binary
      run: go build -v -o ./cmd/server/bin/app ./cmd/server/main.go

    # 4. Start the binary in the background and wait for it to be ready 
    - name: Start Go Binary in Background
      run: |
        chmod +x ./cmd/server/bin/app
        nohup ./cmd/server/bin/app > server.log 2>&1 &

    - name: wait for server, install playwright, and run tests
      run: |
        timeout 30s sh -c 'until nc -z localhost 8080; do sleep 1; done'
        npm ci -y
        npm install -g playwright
        npx playwright install --with-deps
        npx playwright test 

        


